#pragma once

#define CURRENT_TRANSACTION_VERSION 1

enum BLOB_TYPE {
  BLOB_TYPE_CRYPTONOTE = 0,
  BLOB_TYPE_FORKNOTE1 = 1,
  BLOB_TYPE_FORKNOTE2 = 2,
  BLOB_TYPE_CRYPTONOTE_LIGHT = 3,
  BLOB_TYPE_CRYPTONOTE_HEAVY = 4
};
